version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    ports:
      - 80:80
    depends_on:
      - "mysql":
        condition: service_healthy

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'deming'
      MYSQL_USER: 'deming_user'
      MYSQL_PASSWORD: 'demPasssword-123'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3