version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    environment:
      ### PLEASE DISABLE FOR PRODUCTION
      - USE_DEMO_DATA=1
      ### PLEASE DISABLE FOR PRODUCTION
      #- RESET_DB=EN #EN OR FR
      ### PLEASE AFTER ONE RUN DISABLE FOR OPTIMIZATION
      - UPLOAD_DB_ISO27001=FR #EN OR FR
      ### PLEASE AFTER ONE RUN DISABLE FOR OPTIMIZATION
      - INITIAL_DB=FR #EN OR FR
    ports:
      - 80:80
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'deming'
      MYSQL_USER: 'deming_user'
      MYSQL_PASSWORD: 'demPasssword-123'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
### PLEASE ENABLE FOR PERSISTENT DATABASE DATA
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: